export const project = [
    {
        id: 1,
        name: 'agua potable',
        abstrac: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget urna maximus, ultrices neque quis, malesuada tortor. Sed imperdiet, dolor in scelerisque aliquet, dolor nisi molestie nibh, vel varius elit urna a magna. Maecenas elementum posuere facilisis. Proin ultrices, arcu non fermentum tristique, felis dui mattis turpis, condimentum tincidunt orci nulla et elit. Phasellus elementum porttitor felis, in pulvinar eros feugiat quis. Nunc mollis neque eu mollis lobortis. Nullam a est sit amet lectus consectetur accumsan.',
        images: 'http://ongcausasnobles.cl/wp-content/uploads/2020/07/causasnobles.png',
        location: 'Peru',
        cost: 500000,
        completed : false,
        user:"Juan",
    },
    {
        id: 2,
        name:'electricidad',
        abstrac: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget urna maximus, ultrices neque quis, malesuada tortor. Sed imperdiet, dolor in scelerisque aliquet, dolor nisi molestie nibh, vel varius elit urna a magna. Maecenas elementum posuere facilisis. Proin ultrices, arcu non fermentum tristique, felis dui mattis turpis, condimentum tincidunt orci nulla et elit. Phasellus elementum porttitor felis, in pulvinar eros feugiat quis. Nunc mollis neque eu mollis lobortis. Nullam a est sit amet lectus consectetur accumsan.',
        images: 'https://ayudaenaccion.org/uploads/2022/02/RS12046_IMG-20190508-WA0002.jpg',
        location: 'Colombia',
        cost: 200000,
        completed : true,
        user: "Alejandro",
    },
    {
        id: 3,
        name: 'alimentacion',
        abstrac: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget urna maximus, ultrices neque quis, malesuada tortor. Sed imperdiet, dolor in scelerisque aliquet, dolor nisi molestie nibh, vel varius elit urna a magna. Maecenas elementum posuere facilisis. Proin ultrices, arcu non fermentum tristique, felis dui mattis turpis, condimentum tincidunt orci nulla et elit. Phasellus elementum porttitor felis, in pulvinar eros feugiat quis. Nunc mollis neque eu mollis lobortis. Nullam a est sit amet lectus consectetur accumsan.',
        images:'https://images.ecestaticos.com/MWLb9v9Lf33repBmyeLoY6lXuJA=/0x0:1254x836/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2Fdbd%2F0bf%2Fcf6%2Fdbd0bfcf66e3dc6778dd2afade6f8604.jpg',
        location: 'Brazil',
        cost: 150000,
        completed : false,
        user: "Daniel",
    },
    {
        id: 4,
        name: 'agricultura sostenible',
        abstrac: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget urna maximus, ultrices neque quis, malesuada tortor. Sed imperdiet, dolor in scelerisque aliquet, dolor nisi molestie nibh, vel varius elit urna a magna. Maecenas elementum posuere facilisis. Proin ultrices, arcu non fermentum tristique, felis dui mattis turpis, condimentum tincidunt orci nulla et elit. Phasellus elementum porttitor felis, in pulvinar eros feugiat quis. Nunc mollis neque eu mollis lobortis. Nullam a est sit amet lectus consectetur accumsan.',
        images: 'https://www.bancomundial.org/content/dam/photos/780x439/2020/nov-1/CropfieldGTMariaFleischmann.jpg',
        location: 'Argentina',
        cost:600000,
        completed : false,
        user: "Alejandro",
    },
    {
        id: 5,
        name: 'Escuela para niños',
        abstrac: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget urna maximus, ultrices neque quis, malesuada tortor. Sed imperdiet, dolor in scelerisque aliquet, dolor nisi molestie nibh, vel varius elit urna a magna. Maecenas elementum posuere facilisis. Proin ultrices, arcu non fermentum tristique, felis dui mattis turpis, condimentum tincidunt orci nulla et elit. Phasellus elementum porttitor felis, in pulvinar eros feugiat quis. Nunc mollis neque eu mollis lobortis. Nullam a est sit amet lectus consectetur accumsan.',
        images: 'https://www.noticiasensalud.com/wp-content/uploads/2021/07/Servicios-centros-e-informaciones-de-interes-para-garantizar-nuestra-salud-1000x600.png',
        location: 'Haiti',
        cost: 7000000,
        completed : false,
        user: "Braian",
    },
    {
        id: 6,
        name: 'agricultura en Rio',
        abstrac: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget urna maximus, ultrices neque quis, malesuada tortor. Sed imperdiet, dolor in scelerisque aliquet, dolor nisi molestie nibh, vel varius elit urna a magna. Maecenas elementum posuere facilisis. Proin ultrices, arcu non fermentum tristique, felis dui mattis turpis, condimentum tincidunt orci nulla et elit. Phasellus elementum porttitor felis, in pulvinar eros feugiat quis. Nunc mollis neque eu mollis lobortis. Nullam a est sit amet lectus consectetur accumsan.',
        images: 'https://www.noticiasensalud.com/wp-content/uploads/2021/07/Servicios-centros-e-informaciones-de-interes-para-garantizar-nuestra-salud-1000x600.png',
        location: 'Brasil',
        cost: 9000000,
        completed : true,
        user: "Alejandro", 
    },
    {
        id: 7,
        name: 'salud en casanae',
        abstrac: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget urna maximus, ultrices neque quis, malesuada tortor. Sed imperdiet, dolor in scelerisque aliquet, dolor nisi molestie nibh, vel varius elit urna a magna. Maecenas elementum posuere facilisis. Proin ultrices, arcu non fermentum tristique, felis dui mattis turpis, condimentum tincidunt orci nulla et elit. Phasellus elementum porttitor felis, in pulvinar eros feugiat quis. Nunc mollis neque eu mollis lobortis. Nullam a est sit amet lectus consectetur accumsan.',
        images: 'https://www.noticiasensalud.com/wp-content/uploads/2021/07/Servicios-centros-e-informaciones-de-interes-para-garantizar-nuestra-salud-1000x600.png',
        location: 'Colombia',
        cost: 1000000,
        completed : false,
        user: "Daniel",
    },
    {
        id: 8,
        name: 'salud para todos',
        abstrac: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget urna maximus, ultrices neque quis, malesuada tortor. Sed imperdiet, dolor in scelerisque aliquet, dolor nisi molestie nibh, vel varius elit urna a magna. Maecenas elementum posuere facilisis. Proin ultrices, arcu non fermentum tristique, felis dui mattis turpis, condimentum tincidunt orci nulla et elit. Phasellus elementum porttitor felis, in pulvinar eros feugiat quis. Nunc mollis neque eu mollis lobortis. Nullam a est sit amet lectus consectetur accumsan.',
        images: 'https://www.noticiasensalud.com/wp-content/uploads/2021/07/Servicios-centros-e-informaciones-de-interes-para-garantizar-nuestra-salud-1000x600.png',
        location: 'Paraguay',
        cost: 5000000,
        completed : false,
        user:"Juan",
    }
]

export const users = [
    {
        id: 1,
        name: "Juan", 
    },
    {
        id: 2,
        name: "Daniel", 
    },
    {
        id:3,
        name: "Alejandro", 
    },
    {
        id: 4,
        name: "Braian", 
    },
]